// client/src/components/vines/Vine.vue
<template>
  <div class="vine">
	<video v-if="clicked" ref="video" loop autoplay v-on:click="toggleVideo">
      <source :src="vine.vineUrl" type="video/mp4">
    </video>
	<img v-if="!clicked" v-on:click="loadVideo" :src="vine.thumbnailUrl" />
  </div>
</template>

<script>
export default {
	name: 'Vine',
	props: ['vine'],
	data() {
		return {
			clicked: false,
			dataDir: ''
		}
	},
	methods: {
		toggleVideo() {
			if (this.$refs.video.paused) {
				this.$refs.video.play()
			} else {
				this.$refs.video.pause()
			}
		},
		loadVideo() {
			this.clicked = true
		}
	},
	mounted() {
		this.dataDir = `${process.env.VUE_APP_API_STATIC}/${this.vine.videoId}`
	}
}
</script>

<style scoped>
.vine {
	display: flex;
	width: 33.3333%;
	cursor: pointer;
}

.vine video {
	width: 100%;
}

video::-internal-media-controls-overlay-cast-button {
	display: none;
}

@media screen and (max-width: 500px) {
	.vine {
		width: 50%;
	}
}
</style>

// client/src/components/vines/Vine.tsx
import React, { useState, useRef } from 'react';
import IVine from '../../entities/Vine';

interface VineProps {
    data: IVine;
}

const Vine: React.FC<VineProps> = ({ data }) => {
    const videoRef = useRef<HTMLVideoElement | null>(null);
    const [clicked, setClicked] = useState<boolean>(false);

    const loadVideo = () => {
        setClicked(true);

        if (videoRef && videoRef.current) {
            videoRef.current.addEventListener('loadeddata', (e) => {
                videoRef?.current?.play();
            });

            videoRef.current.load();
        }
    };

    const toggleVideo = () => {
        if (videoRef && videoRef.current) {
            if (videoRef.current.paused) {
                videoRef.current.play();
            } else {
                videoRef.current.pause();
            }
        }
    };

    return (
        <div className="overflow-hidden rounded-md cursor-pointer">
            <video className={clicked ? '' : 'hidden'} ref={videoRef} loop preload="none" onClick={toggleVideo}>
                <source src={data.vineUrl} type="video/mp4" />
            </video>
            <img className={`w-full${clicked ? ' hidden' : ''}`} src={data.thumbnailUrl} alt={data.title} onClick={loadVideo} onKeyPress={loadVideo} role="presentation" />
        </div>
    );
};

export default Vine;
